### ISSUE TITLE
Pressing Spacebar to continue/pause playback.

### ISSUE THREAD

**Issue by shortenjukebox** [CD1212/Doughnut#14]
Self-explanatory. All media players have it, I was surprised that media keys work but not `Spacebar`.

**Comment by CD1212** [comment]
Hi @shortenjukebox thanks so much for logging all of these issues, they are really great suggestions and I will look to factor them all in over the next several weeks.

This issue in particular is resolved by a pull request #10 which is in master but not yet deployed to a release.

**Comment by shortenjukebox** [comment]
Ah my mistake, I didn’t see that.
