### ISSUE TITLE
Clicking episode multiple times plays multiple instances of the episode.

### ISSUE THREAD

**Issue by shortenjukebox** [CD1212/Doughnut#17]
Doughnut 1.0.2 (8), macOS 10.14.3 (18D109)

I tried clicking an episode twice to play it, and this happened. Once the episodes start playing, I am only able to stop playing one instance.

**Comment by KnoxWare** [comment]
Similar issue. Clicking other episodes to play while another is playing will result in both tracks playing at the same time.  The only way to stop the two tracks from playing at the same time is to restart the application.
